import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Send, AlertCircle } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import {
  DEFAULT_MONTHLY_PACKAGE_KEY,
  MONTHLY_PACKAGE_KEYS,
  MONTHLY_SERVICE_PACKAGES,
  type MonthlyPackageKey,
} from "@shared/servicePackages";
import {
  buildDiagnosisProposalFocus,
  buildDiagnosisProposalJustification,
  buildDiagnosisProposalPriority,
  buildDiagnosisProposalProgressSignals,
  buildDiagnosisProposalRecommendedPlan,
  buildDiagnosisProposalSessionStructure,
  buildDiagnosisProposalWhyEntry,
  normalizeProposalPhaseSupportEvidence,
  normalizeProposalPlacementEvidence,
  normalizeProposalTrainingAction,
} from "@shared/diagnosisProposalCopy";

interface ParentOnboardingProposalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  studentName: string;
  studentId: string;
  tutorName?: string;
  identitySheetData?: unknown;
  parentTopics?: string;
}

export default function ParentOnboardingProposal({
  open,
  onOpenChange,
  studentName,
  studentId,
}: ParentOnboardingProposalProps) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const studentFirstName = studentName.trim().split(/\s+/)[0] || "Your child";
  const [sending, setSending] = useState(false);
  const [selectedPackageKey, setSelectedPackageKey] = useState<MonthlyPackageKey>(DEFAULT_MONTHLY_PACKAGE_KEY);
  const selectedPackage = MONTHLY_SERVICE_PACKAGES[selectedPackageKey];

  // Fetch latest intro drill
  const { data: drillDataRaw, isLoading: drillLoading, error: drillError } = useQuery({
    queryKey: ["/api/tutor/students", studentId, "latest-intro-drill"],
    queryFn: async () => {
      const res = await apiRequest("GET", `/api/tutor/students/${studentId}/latest-intro-drill`);
      return res.json();
    },
    enabled: open && !!studentId,
  });

  const drillData = drillDataRaw as any;
  const diagnosisRunId = String(drillData?.id || "").trim();
  const isEvidenceNativeDiagnosis =
    drillData?.summary?.diagnosisEngine === "evidence_native_v2" ||
    drillData?.diagnosisEngine === "evidence_native_v2" ||
    drillData?.diagnosisMode === "evidence_native";

  const { data: diagnosisRunDataRaw, isLoading: diagnosisRunLoading } = useQuery({
    queryKey: ["/api/tutor/evidence-complete-diagnosis", diagnosisRunId],
    queryFn: async () => {
      const res = await apiRequest(
        "GET",
        `/api/tutor/evidence-complete-diagnosis/${diagnosisRunId}`,
      );
      return res.json();
    },
    enabled: open && !!diagnosisRunId && isEvidenceNativeDiagnosis,
  });

  const diagnosisRunData = diagnosisRunDataRaw as any;

  // Evidence-native diagnosis classifies entry phase/stability from observed behavior.
  // Numeric scores have no diagnosis decision authority.
  const deriveTrainingEntryPhase = (diagnosisPhase: string, _stability: string): string => {
    return diagnosisPhase;
  };

  const handleSendProposal = async () => {
    if (!drillData) {
      toast({
        title: "Missing Intro Drill",
        description: "No intro drill data found. Please complete the intro session first.",
        variant: "destructive",
      });
      return;
    }

    setSending(true);
    try {
      const diagnosisPhase = drillData?.summary?.phase || drillData?.phase || "Clarity";
      const stability = drillData?.summary?.stability || drillData?.stability || "Low";
      const topic = drillData?.introTopic || drillData?.topic || drillData?.summary?.topic || "";
      const trainingEntryPhase = deriveTrainingEntryPhase(diagnosisPhase, stability);

      const placementEvidence = normalizeProposalPlacementEvidence(
        drillData?.summary?.placementEvidence,
      );
      const nextAction =
        normalizeProposalTrainingAction(drillData?.summary?.nextAction) || "Continue phase work";
      const recommendedPlan = buildDiagnosisProposalRecommendedPlan({
        topic: topic || "primary diagnostic topic",
        phase: trainingEntryPhase,
        stability,
        nextAction,
      });
      const justification = buildDiagnosisProposalJustification({
        topic: topic || "the diagnostic topic",
        phase: diagnosisPhase,
        stability,
        reason:
          drillData?.summary?.reason ||
          "The entry state was resolved from the student's observed response behavior.",
        nextAction,
        placementEvidence,
      });

      const response = await apiRequest("POST", "/api/tutor/proposal", {
        studentId,
        autoGeneratedFromIntroDrill: true,
        introDrillId: drillData.id,
        recommendedPlan,
        justification,
        topicConditioningTopic: topic,
        topicConditioningEntryPhase: trainingEntryPhase,
        topicConditioningStability: stability,
        packageKey: selectedPackageKey,
      });

      toast({
        title: "Training Plan Sent!",
        description: `The training plan for ${studentFirstName} has been sent to their parent.`,
        duration: 5000,
      });

      await queryClient.invalidateQueries({ queryKey: ["/api/tutor/pod"] });
      await queryClient.invalidateQueries({
        queryKey: ["/api/tutor/students", studentId, "workflow-state"],
        refetchType: "active",
      });

      onOpenChange(false);
    } catch (error) {
      toast({
        title: "Failed to Send",
        description: error instanceof Error ? error.message : "An unexpected error occurred",
        variant: "destructive",
        duration: 5000,
      });
    } finally {
      setSending(false);
    }
  };

  if (!open) return null;

  const loading = drillLoading;
  const error = drillError;

  if (loading) {
    return (
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Training Plan From Intro Drill</DialogTitle>
          </DialogHeader>
          <div className="py-8 text-center text-muted-foreground">Loading intro drill data...</div>
        </DialogContent>
      </Dialog>
    );
  }

  if (error || !drillData) {
    return (
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Training Plan From Intro Drill</DialogTitle>
          </DialogHeader>
          <div className="py-6 space-y-3">
            <div className="flex items-start gap-2 p-3 bg-destructive/10 border border-destructive/20 rounded-md">
              <AlertCircle className="w-4 h-4 text-destructive mt-0.5 flex-shrink-0" />
              <div className="text-sm text-destructive">
                <p className="font-semibold">No Intro Drill Found</p>
                <p className="text-xs mt-1">Please complete the intro session drill first before generating a training plan.</p>
              </div>
            </div>
            <div className="flex justify-end">
              <Button variant="outline" onClick={() => onOpenChange(false)}>
                Close
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    );
  }

  const entryPhase = drillData?.summary?.phase || drillData?.phase || drillData?.phaseObserved || "Clarity";
  const startingSignal =
    drillData?.startingPhase ||
    drillData?.responseSnapshot?.startingPhase ||
    drillData?.summary?.startingPhase ||
    diagnosisRunData?.startingPhase ||
    (isEvidenceNativeDiagnosis && diagnosisRunLoading ? "Loading…" : "Not recorded");
  const stability = drillData?.summary?.stability || drillData?.stability || drillData?.stabilityObserved || "Low";
  const topic = drillData?.introTopic || drillData?.topic || "Current class topic";
  const trainingEntryPhase = deriveTrainingEntryPhase(entryPhase, stability);
  const placementEvidence = normalizeProposalPlacementEvidence(
    drillData?.summary?.placementEvidence,
  );
  const phaseSupportEvidence = normalizeProposalPhaseSupportEvidence(
    drillData?.summary?.phaseStates,
    trainingEntryPhase,
  );
  const nextAction =
    normalizeProposalTrainingAction(drillData?.summary?.nextAction) || "Continue phase work";
  const focusArea = buildDiagnosisProposalFocus({
    studentFirstName,
    phase: trainingEntryPhase,
    stability,
  });
  const whyEntry = buildDiagnosisProposalWhyEntry({
    phase: entryPhase,
    placementEvidence,
    reason: drillData?.summary?.reason,
  });
  const priority = buildDiagnosisProposalPriority({
    studentFirstName,
    phase: trainingEntryPhase,
    stability,
    nextAction,
    placementEvidence,
  });
  const sessionStructure = buildDiagnosisProposalSessionStructure({
    phase: trainingEntryPhase,
    stability,
    nextAction,
    placementEvidence,
    phaseSupportEvidence,
  });
  const progressSignals = buildDiagnosisProposalProgressSignals({
    phase: trainingEntryPhase,
    stability,
    nextAction,
    placementEvidence,
    phaseSupportEvidence,
  });

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Training Plan From Intro Drill</DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          <div className="bg-primary/10 rounded-lg p-4 border border-primary/20">
            <h3 className="font-bold text-sm text-center mb-0.5">Training Proposal Ready</h3>
            <p className="text-xs text-center text-muted-foreground">{studentName}</p>
            <p className="text-[11px] text-center text-muted-foreground mt-1">
              Diagnosis ran on: <span className="font-medium text-foreground">{topic}</span>
            </p>
          </div>

          <Card>
            <CardHeader className="pb-2 pt-4 px-4">
              <CardTitle className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Monthly Package
              </CardTitle>
            </CardHeader>
            <CardContent className="px-4 pb-4">
              <RadioGroup
                value={selectedPackageKey}
                onValueChange={(value) => setSelectedPackageKey(value as MonthlyPackageKey)}
                className="grid gap-2 sm:grid-cols-3"
              >
                {MONTHLY_PACKAGE_KEYS.map((packageKey) => {
                  const servicePackage = MONTHLY_SERVICE_PACKAGES[packageKey];
                  return (
                    <Label
                      key={packageKey}
                      htmlFor={`proposal-${packageKey}`}
                      className="flex cursor-pointer items-start gap-2 rounded-lg border p-3 hover:border-primary/50"
                    >
                      <RadioGroupItem id={`proposal-${packageKey}`} value={packageKey} className="mt-0.5" />
                      <span>
                        <span className="block text-sm font-semibold text-foreground">
                          {servicePackage.sessionsPerMonth} sessions
                        </span>
                        <span className="block text-xs text-muted-foreground">
                          {servicePackage.plannedSessionsPerWeek}x weekly - R{servicePackage.amountZar.toLocaleString("en-ZA")}/month
                        </span>
                      </span>
                    </Label>
                  );
                })}
              </RadioGroup>
              <p className="mt-3 text-xs text-muted-foreground">
                Choose the agreed monthly delivery frequency. Diagnosis determines the training entry and first focus; it does not currently choose package frequency.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-2 pt-4 px-4">
              <CardTitle className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Focus Area
              </CardTitle>
            </CardHeader>
            <CardContent className="px-4 pb-4">
              <p className="text-xs leading-5 text-muted-foreground">{focusArea}</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-2 pt-4 px-4">
              <CardTitle className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Why Training Starts Here
              </CardTitle>
            </CardHeader>
            <CardContent className="px-4 pb-4">
              <p className="text-xs leading-5 text-muted-foreground">{whyEntry}</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-2 pt-4 px-4">
              <CardTitle className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                What We Will Work On First
              </CardTitle>
            </CardHeader>
            <CardContent className="px-4 pb-4">
              <p className="text-xs leading-5 text-muted-foreground">{priority}</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-2 pt-4 px-4">
              <CardTitle className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Diagnostic Results
              </CardTitle>
            </CardHeader>
            <CardContent className="px-4 pb-4 space-y-2">
              <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
                <div className="rounded-md border bg-muted/50 p-2">
                  <p className="text-[10px] uppercase text-muted-foreground mb-1">Topic</p>
                  <p className="text-xs font-medium text-foreground">{topic}</p>
                </div>
                <div className="rounded-md border bg-muted/50 p-2">
                  <p className="text-[10px] uppercase text-muted-foreground mb-1">Starting Signal</p>
                  <p className="text-xs font-medium text-foreground">{startingSignal}</p>
                </div>
                <div className="rounded-md border bg-muted/50 p-2">
                  <p className="text-[10px] uppercase text-muted-foreground mb-1">Entry Phase</p>
                  <p className="text-xs font-medium text-foreground">{trainingEntryPhase}</p>
                </div>
                <div className="rounded-md border bg-muted/50 p-2">
                  <p className="text-[10px] uppercase text-muted-foreground mb-1">Stability</p>
                  <p className="text-xs font-medium text-foreground">{stability}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-2 pt-4 px-4">
              <CardTitle className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                How Sessions Will Be Structured
              </CardTitle>
            </CardHeader>
            <CardContent className="px-4 pb-4">
              <ul className="text-xs text-muted-foreground space-y-1 ml-2">
                <li>Cadence: {selectedPackage.plannedSessionsPerWeek} sessions per week ({selectedPackage.sessionsPerMonth} sessions per month)</li>
                {sessionStructure.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-2 pt-4 px-4">
              <CardTitle className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                How Progress Will Be Observed
              </CardTitle>
            </CardHeader>
            <CardContent className="px-4 pb-4">
              <ul className="text-xs text-muted-foreground space-y-1 ml-2">
                {progressSignals.map((signal) => (
                  <li key={signal}>{signal}</li>
                ))}
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="px-4 py-3 space-y-2">
              <p className="text-xs text-muted-foreground">
                <strong className="text-foreground">Important Note</strong> - This training focuses on how the student responds while solving, not only on whether the final answer is correct.
              </p>
              <p className="text-xs text-muted-foreground">
                <strong className="text-foreground">Commitment</strong> - Consistency and active participation are required across the selected {selectedPackage.sessionsPerMonth}-session monthly package. Students are expected to attempt before receiving guidance.
              </p>
            </CardContent>
          </Card>

          <div className="flex gap-2 pt-2">
            <Button
              variant="outline"
              onClick={() => onOpenChange(false)}
            >
              Cancel
            </Button>
            <Button 
              onClick={handleSendProposal} 
              className="flex-1 gap-2"
              disabled={sending}
            >
              <Send className="w-3 h-3" /> 
              {sending ? "Sending..." : "Send to Parent"}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
