import type { CapabilityAssessmentDefinition } from "./capabilityEngine";

export const CLARITY_RETRIEVAL_ASSESSMENT: CapabilityAssessmentDefinition = {
  key: "clarity_retrieval_v1",
  deepDiveKey: "clarity",
  title: "Clarity Retrieval Check",
  evidenceKind: "retrieval",
  passThresholdPercent: 96,
  questions: [
    {
      key: "clarity_retrieval_01",
      competencyKey: "clarity.phase_purpose",
      prompt: "Before any pressure is added, what must the student be able to recognise about the work?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Only the final answer" },
        { key: "b", label: "What is present, the method, and why it works" },
        { key: "c", label: "How fast they can finish" },
        { key: "d", label: "How much discomfort they can tolerate" },
      ],
      correctOptionKeys: ["b"],
      explanation: "Clarity establishes recognition and understanding before later phases add independence, difficulty, and time pressure.",
    },
    {
      key: "clarity_retrieval_02",
      competencyKey: "clarity.vmr_sequence",
      prompt: "Which sequence matches the Clarity operating lens?",
      kind: "sequence",
      options: [
        { key: "vocabulary", label: "Vocabulary" },
        { key: "method", label: "Method" },
        { key: "reason", label: "Reason" },
      ],
      correctOptionKeys: ["vocabulary", "method", "reason"],
      explanation: "The Clarity lens is Vocabulary -> Method -> Reason.",
    },
    {
      key: "clarity_retrieval_03",
      competencyKey: "clarity.identification_set",
      prompt: "What must remain excluded from an Identification rep?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Recognition" },
        { key: "b", label: "Naming the method" },
        { key: "c", label: "Solving the problem" },
        { key: "d", label: "Naming relevant terms" },
      ],
      correctOptionKeys: ["c"],
      explanation: "Identification is recognition without solving.",
    },
    {
      key: "clarity_retrieval_04",
      competencyKey: "clarity.modeling_set",
      prompt: "What is the purpose of Modeling before scored Clarity drilling?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Create a mental map the student can explain back" },
        { key: "b", label: "Measure speed" },
        { key: "c", label: "Create discomfort" },
        { key: "d", label: "Replace all later evidence" },
      ],
      correctOptionKeys: ["a"],
      explanation: "Modeling builds the mental map before scored drilling.",
    },
    {
      key: "clarity_retrieval_05",
      competencyKey: "clarity.light_apply_support",
      prompt: "What kind of support is compatible with Light Apply?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Minimal guidance that preserves the student's own start and execution" },
        { key: "b", label: "Full step-by-step rescue" },
        { key: "c", label: "Unlimited Specialist discretion" },
        { key: "d", label: "Mandatory first-step prompting on every rep" },
      ],
      correctOptionKeys: ["a"],
      explanation: "Light Apply allows minimal guidance, not rescue that manufactures stronger evidence.",
    },
    {
      key: "clarity_retrieval_06",
      competencyKey: "evidence.observation_vs_inference",
      prompt: "Which statement is an observation rather than an inference?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The student is unconfident" },
        { key: "b", label: "The student waited 9 seconds before naming the operation" },
        { key: "c", label: "The student dislikes fractions" },
        { key: "d", label: "The student has poor discipline" },
      ],
      correctOptionKeys: ["b"],
      explanation: "RI evidence records what happened, not an inferred psychological explanation.",
    },
    {
      key: "clarity_retrieval_07",
      competencyKey: "evidence.contamination",
      prompt: "A Specialist supplies most of the method and the student finishes the final step. Which claim is valid?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Independent execution was demonstrated" },
        { key: "b", label: "The performance was assisted and must remain represented as assisted" },
        { key: "c", label: "The assistance can be omitted if the answer is correct" },
        { key: "d", label: "The topic should progress automatically" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["a", "c"],
      explanation: "Assisted performance cannot be rewritten as independent evidence.",
    },
    {
      key: "clarity_retrieval_08",
      competencyKey: "system.authority",
      prompt: "After a drill is submitted, who owns the final topic-state movement?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The Specialist" },
        { key: "b", label: "The parent" },
        { key: "c", label: "The RI system using captured evidence" },
        { key: "d", label: "Whoever wants the fastest progress" },
      ],
      correctOptionKeys: ["c"],
      criticalFailOptionKeys: ["a", "d"],
      explanation: "The system, not Specialist intuition, controls final state movement.",
    },
    {
      key: "clarity_retrieval_09",
      competencyKey: "clarity.constraints",
      prompt: "Select every condition that Clarity protects.",
      kind: "multi_select",
      options: [
        { key: "a", label: "No Boss Battles" },
        { key: "b", label: "No time pressure" },
        { key: "c", label: "No skipping layers" },
        { key: "d", label: "Repeated timer pressure" },
      ],
      correctOptionKeys: ["a", "b", "c"],
      explanation: "Clarity operates before high-difficulty and timed-pressure conditions.",
    },
    {
      key: "clarity_retrieval_10",
      competencyKey: "clarity.rep_purpose",
      prompt: "Why does a defined set contain repeated reps?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Each rep is another controlled evidence opportunity under the same purpose" },
        { key: "b", label: "To let the Specialist change objectives between reps" },
        { key: "c", label: "To guarantee eventual correctness" },
        { key: "d", label: "To make the session longer" },
      ],
      correctOptionKeys: ["a"],
      explanation: "Repeated reps test whether a response is repeatable under the same defined condition.",
    },
    {
      key: "clarity_retrieval_11",
      competencyKey: "evidence.logging_integrity",
      prompt: "What should happen to an earlier weak rep after the student improves later?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Rewrite it as clear" },
        { key: "b", label: "Preserve the original evidence and record later improvement separately" },
        { key: "c", label: "Delete it" },
        { key: "d", label: "Average it into a stronger label manually" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["a", "c"],
      explanation: "Historical evidence remains historical evidence; later improvement does not rewrite the earlier rep.",
    },
    {
      key: "clarity_retrieval_12",
      competencyKey: "clarity.progression",
      prompt: "Where can qualifying Clarity evidence progress a topic next?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Structured Execution at Low, when the engine determines the gate is met" },
        { key: "b", label: "Directly to Time Pressure Stability" },
        { key: "c", label: "Any phase chosen by the Specialist" },
        { key: "d", label: "Nowhere" },
      ],
      correctOptionKeys: ["a"],
      explanation: "Clarity progresses into Structured Execution through system-controlled progression.",
    },
    {
      key: "clarity_retrieval_13",
      competencyKey: "clarity.recognition_boundary",
      prompt: "A student begins calculating during a recognition-only opportunity. What must the Specialist preserve?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The recognition-only boundary" },
        { key: "b", label: "The student's momentum at any cost" },
        { key: "c", label: "The final answer" },
        { key: "d", label: "A timer" },
      ],
      correctOptionKeys: ["a"],
      explanation: "The Specialist protects the condition the rep is designed to test.",
    },
    {
      key: "clarity_retrieval_14",
      competencyKey: "discernment.escalation_boundary",
      prompt: "What should a Specialist do when the live situation is outside the authorised recipe?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Invent the missing rule" },
        { key: "b", label: "Record the deviation, preserve what is safe, and escalate" },
        { key: "c", label: "Change the student's phase manually" },
        { key: "d", label: "Mark the session successful and continue" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["c", "d"],
      explanation: "Discernment includes respecting the boundary of Specialist authority.",
    },
    {
      key: "clarity_retrieval_15",
      competencyKey: "clarity.transfer",
      prompt: "A student can explain the method but needs the Specialist to initiate each solution. Which distinction matters?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Understanding is present, but independent execution remains unproven" },
        { key: "b", label: "Understanding automatically proves independence" },
        { key: "c", label: "A timer should be introduced immediately" },
        { key: "d", label: "The prompts should be ignored in the evidence" },
      ],
      correctOptionKeys: ["a"],
      explanation: "RI separates understanding from independent execution rather than collapsing them into one claim.",
    },
  ],
};
