import type { CapabilityAssessmentDefinition } from "./capabilityEngine";

export const CLARITY_STRUCTURED_TRANSFER_ASSESSMENT: CapabilityAssessmentDefinition = {
  key: "clarity_structured_transfer_v1",
  deepDiveKey: "mixed",
  title: "Interleaved Transfer Check - Foundation Phases",
  evidenceKind: "transfer",
  passThresholdPercent: 96,
  questions: [
    {
      key: "transfer_foundation_01",
      competencyKey: "clarity.recognition_boundary",
      deepDiveKey: "clarity",
      prompt: "The active rep is meant only to establish whether the student can identify the type of problem and name the method. The student starts calculating immediately. What should the Specialist do?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Let the calculation continue because it shows confidence" },
        { key: "b", label: "Return the rep to identification only so the intended evidence condition is preserved" },
        { key: "c", label: "Give a hint and mark the rep clear" },
        { key: "d", label: "Skip the rep" },
      ],
      correctOptionKeys: ["b"],
      explanation: "The condition of the rep must be preserved; solving would change what the rep is measuring.",
    },
    {
      key: "transfer_foundation_02",
      competencyKey: "structured_execution.required_structure",
      deepDiveKey: "structured_execution",
      prompt: "A student gives the correct answer immediately but cannot state the method chain they used. Which conclusion is strongest?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The structured response is proven because the answer is correct" },
        { key: "b", label: "The answer may be correct, but required structure has not been demonstrated" },
        { key: "c", label: "The student is ready for time pressure" },
        { key: "d", label: "The Specialist should infer the missing steps" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["d"],
      explanation: "RI separates final correctness from evidence of a repeatable method chain.",
    },
    {
      key: "transfer_foundation_03",
      competencyKey: "evidence.observation_vs_inference",
      deepDiveKey: "clarity",
      prompt: "Which session note is safe to preserve as evidence?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The student was scared of the question" },
        { key: "b", label: "The student paused, reread the expression twice, then named the wrong operation" },
        { key: "c", label: "The student has weak confidence" },
        { key: "d", label: "The student does not care enough" },
      ],
      correctOptionKeys: ["b"],
      explanation: "Observable behavior is evidence; psychological interpretation is not.",
    },
    {
      key: "transfer_foundation_04",
      competencyKey: "structured_execution.independent_execution",
      deepDiveKey: "structured_execution",
      prompt: "A student pauses midway through a no-help execution attempt. What best protects the purpose of the rep?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Immediately provide the next step" },
        { key: "b", label: "Hold the no-help condition long enough to observe whether the student can continue independently" },
        { key: "c", label: "End the rep before more evidence appears" },
        { key: "d", label: "Change the student's state manually" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["d"],
      explanation: "The pause is part of the evidence. Rescue would contaminate the test of independent continuation.",
    },
    {
      key: "transfer_foundation_05",
      competencyKey: "evidence.contamination",
      deepDiveKey: "structured_execution",
      prompt: "The Specialist gives the first two steps during an attempt intended to test unaided execution, and the student completes the rest. What may be recorded?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Independent execution because most of the work was completed by the student" },
        { key: "b", label: "Assisted execution; the prompts must remain visible in the evidence" },
        { key: "c", label: "A clear independent result if the final answer is correct" },
        { key: "d", label: "Whatever label helps progression" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["a", "c", "d"],
      explanation: "The support given changes the evidentiary meaning of the rep and cannot be erased.",
    },
    {
      key: "transfer_foundation_06",
      competencyKey: "clarity.light_apply_support",
      deepDiveKey: "clarity",
      prompt: "The student understands the method but needs a small prompt to connect the explanation to active solving. Which support is most aligned?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Minimal guidance while preserving the student's own start and structured work" },
        { key: "b", label: "Full step-by-step teaching until completion" },
        { key: "c", label: "Introduce a timer" },
        { key: "d", label: "Give the answer and ask for explanation afterward" },
      ],
      correctOptionKeys: ["a"],
      explanation: "Minimal support can be compatible with active Clarity work so long as it does not manufacture independence.",
    },
    {
      key: "transfer_foundation_07",
      competencyKey: "structured_execution.variation_control",
      deepDiveKey: "structured_execution",
      prompt: "Three same-form problems are completed correctly. You now need evidence that the method survives a changed surface form. What should happen next?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Repeat the identical form again" },
        { key: "b", label: "Present a changed-form problem without pointing out what changed" },
        { key: "c", label: "Explain the variation first" },
        { key: "d", label: "Record the same-form reps as changed-form transfer" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["d"],
      explanation: "Changed-form transfer requires an actual variation condition, not relabelled same-form repetition.",
    },
    {
      key: "transfer_foundation_08",
      competencyKey: "system.authority",
      deepDiveKey: "clarity",
      prompt: "The Specialist believes the student is ready to move forward, but the captured evidence has not satisfied the system gate. What is the correct action?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Override the system because the Specialist saw the session live" },
        { key: "b", label: "Preserve the evidence and let the system-controlled progression rule stand" },
        { key: "c", label: "Ask the parent to choose" },
        { key: "d", label: "Change the phase quietly and continue" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["a", "d"],
      explanation: "Specialists observe and submit evidence; final state authority remains with the defined system.",
    },
    {
      key: "transfer_foundation_09",
      competencyKey: "structured_execution.phase_boundary",
      deepDiveKey: "structured_execution",
      prompt: "The student still needs heavy explanation of the method before every attempt. What is the strongest interpretation?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Keep calling the assisted work independent until enough reps accumulate" },
        { key: "b", label: "The prerequisite understanding may not be stable enough for unaided execution; preserve the evidence and allow the system to determine state" },
        { key: "c", label: "Increase difficulty" },
        { key: "d", label: "Add time pressure" },
      ],
      correctOptionKeys: ["b"],
      explanation: "Heavy remodelling suggests a prerequisite capability gap rather than evidence of independent execution.",
    },
    {
      key: "transfer_foundation_10",
      competencyKey: "clarity.rep_purpose",
      deepDiveKey: "clarity",
      prompt: "A first attempt looks strong. Why might another rep still be required under the same defined condition?",
      kind: "single_choice",
      options: [
        { key: "a", label: "To establish repeatability instead of trusting one isolated success" },
        { key: "b", label: "To fill time" },
        { key: "c", label: "To let the Specialist change the purpose" },
        { key: "d", label: "To guarantee a perfect score" },
      ],
      correctOptionKeys: ["a"],
      explanation: "Repeated controlled opportunities distinguish repeatable capability from a single good event.",
    },
    {
      key: "transfer_foundation_11",
      competencyKey: "evidence.logging_integrity",
      deepDiveKey: "structured_execution",
      prompt: "The student improves on the final two attempts after a weak first attempt. How should the record be handled?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Rewrite the first attempt as strong so the session looks consistent" },
        { key: "b", label: "Preserve the weak first attempt and record the later stronger attempts separately" },
        { key: "c", label: "Delete the first attempt" },
        { key: "d", label: "Only report the best result" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["a", "c", "d"],
      explanation: "Later improvement does not alter historical evidence.",
    },
    {
      key: "transfer_foundation_12",
      competencyKey: "structured_execution.repeatability",
      deepDiveKey: "structured_execution",
      prompt: "A student executes the method correctly once, then loses the sequence on the next two similar problems. Which claim is supportable?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Repeatable execution is established" },
        { key: "b", label: "There is one successful event, but repeatability is not established" },
        { key: "c", label: "The topic should progress because at least one rep was correct" },
        { key: "d", label: "The weak reps can be ignored" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["d"],
      explanation: "RI distinguishes isolated success from stable repeatability.",
    },
    {
      key: "transfer_foundation_13",
      competencyKey: "clarity.transfer",
      deepDiveKey: "clarity",
      prompt: "The student accurately explains what the problem is and why the method works, but cannot start solving without a prompt. What is the strongest conclusion?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Understanding is demonstrated, while independent execution remains unproven" },
        { key: "b", label: "Full independent execution is demonstrated" },
        { key: "c", label: "The student needs time pressure" },
        { key: "d", label: "The prompt should be ignored" },
      ],
      correctOptionKeys: ["a"],
      explanation: "The architecture deliberately separates understanding from independent execution.",
    },
    {
      key: "transfer_foundation_14",
      competencyKey: "discernment.escalation_boundary",
      deepDiveKey: "structured_execution",
      prompt: "A situation occurs that is not covered by the active recipe, and continuing would require the Specialist to invent a new rule. What is the correct posture?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Invent the rule if it seems reasonable" },
        { key: "b", label: "Preserve what is safe, record the deviation, and escalate" },
        { key: "c", label: "Alter the student's state manually" },
        { key: "d", label: "Mark the work successful to avoid disruption" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["c", "d"],
      explanation: "Capability includes respecting the boundary of authority and escalating appropriately.",
    },
    {
      key: "transfer_foundation_15",
      competencyKey: "structured_execution.progression",
      deepDiveKey: "structured_execution",
      prompt: "Repeated independent execution and changed-form transfer are now strong enough to satisfy the active progression rule. What happens next?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The Specialist manually selects the next phase" },
        { key: "b", label: "The system evaluates the captured evidence and controls the next state movement" },
        { key: "c", label: "The student chooses the next phase" },
        { key: "d", label: "Every strong result jumps directly to timed work" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["a"],
      explanation: "Even after strong execution evidence, progression remains system-controlled.",
    },
  ],
};
