import type { CapabilityAssessmentDefinition } from "./capabilityEngine";

export const CLARITY_MASTERY_ASSESSMENT: CapabilityAssessmentDefinition = {
  key: "clarity_mastery_v1",
  deepDiveKey: "clarity",
  title: "Clarity Mastery Check",
  evidenceKind: "mastery",
  passThresholdPercent: 96,
  questions: [
    {
      key: "clarity_purpose_01",
      competencyKey: "clarity.phase_purpose",
      prompt: "What is Clarity trying to establish before pressure is introduced?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Fast completion of difficult problems" },
        { key: "b", label: "Clear recognition of what is present, the method, and why it works" },
        { key: "c", label: "Tolerance for uncertainty" },
        { key: "d", label: "Performance under a timer" },
      ],
      correctOptionKeys: ["b"],
      explanation: "Clarity protects recognition and understanding before independent execution, discomfort, or time pressure are added.",
    },
    {
      key: "clarity_recognition_02",
      competencyKey: "clarity.recognition_boundary",
      prompt: "During a recognition-only set, the student begins solving. What should the Specialist do?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Allow the solution because the student appears confident" },
        { key: "b", label: "Stop the solving and return the rep to recognition only" },
        { key: "c", label: "Give one hint and continue solving" },
        { key: "d", label: "Skip the rep and mark it clear" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["d"],
      explanation: "Recognition sets must remain recognition-only. A rep cannot be marked clear when the required protocol was not observed.",
    },
    {
      key: "clarity_support_03",
      competencyKey: "clarity.light_apply_support",
      prompt: "Which support is permitted during Clarity Light Apply?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Step-by-step guidance until the answer is complete" },
        { key: "b", label: "Minimal guidance while preserving an independent start and structured execution" },
        { key: "c", label: "No interaction of any kind" },
        { key: "d", label: "The Specialist may choose any support they think is useful" },
      ],
      correctOptionKeys: ["b"],
      explanation: "Light Apply permits minimal guidance, but not step-by-step rescue or free-form Specialist discretion.",
    },
    {
      key: "clarity_evidence_04",
      competencyKey: "evidence.observation_vs_inference",
      prompt: "Which entry is valid observed evidence?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The student was anxious about algebra" },
        { key: "b", label: "The student paused for 12 seconds, then named the wrong operation" },
        { key: "c", label: "The student lacks confidence" },
        { key: "d", label: "The student probably forgot everything" },
      ],
      correctOptionKeys: ["b"],
      explanation: "RI evidence records observable behavior, not psychological inference.",
    },
    {
      key: "clarity_contamination_05",
      competencyKey: "evidence.contamination",
      prompt: "The Specialist gives the first two steps, then the student completes the problem correctly. How should that performance be treated?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Independent clear evidence because the final answer was correct" },
        { key: "b", label: "Assisted performance that cannot be treated as independent evidence" },
        { key: "c", label: "Automatically High Maintenance" },
        { key: "d", label: "The Specialist may decide based on intuition" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["a"],
      explanation: "Assisted performance must never be recorded as independent evidence.",
    },
    {
      key: "clarity_authority_06",
      competencyKey: "system.authority",
      prompt: "Who determines final topic-state movement after a valid drill submission?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The Specialist based on professional instinct" },
        { key: "b", label: "The parent" },
        { key: "c", label: "The deterministic RI system from captured evidence" },
        { key: "d", label: "Whichever option produces faster progress" },
      ],
      correctOptionKeys: ["c"],
      criticalFailOptionKeys: ["a", "d"],
      explanation: "The Specialist captures evidence. The system controls final state movement.",
    },
    {
      key: "clarity_sequence_07",
      competencyKey: "clarity.vmr_sequence",
      prompt: "Put the Clarity operating lens in the correct order.",
      kind: "sequence",
      options: [
        { key: "vocabulary", label: "Vocabulary" },
        { key: "method", label: "Method" },
        { key: "reason", label: "Reason" },
      ],
      correctOptionKeys: ["vocabulary", "method", "reason"],
      explanation: "The live Clarity training sequence is Vocabulary -> Method -> Reason.",
    },
    {
      key: "clarity_identification_08",
      competencyKey: "clarity.identification_set",
      prompt: "What is the purpose of the Identification training set?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Recognition without solving" },
        { key: "b", label: "Speed under time pressure" },
        { key: "c", label: "Open-ended teaching" },
        { key: "d", label: "Boss-battle difficulty" },
      ],
      correctOptionKeys: ["a"],
      explanation: "Identification tests terms, type, steps, and reason without allowing solving.",
    },
    {
      key: "clarity_modeling_09",
      competencyKey: "clarity.modeling_set",
      prompt: "Which statement best describes Modeling in Clarity training?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The Specialist models Vocabulary -> Method -> Reason and the student explains back" },
        { key: "b", label: "The student solves three timed problems independently" },
        { key: "c", label: "The Specialist tests discomfort tolerance" },
        { key: "d", label: "The student chooses the method without any preparation" },
      ],
      correctOptionKeys: ["a"],
      explanation: "Modeling builds the mental map before scored execution checks.",
    },
    {
      key: "clarity_progression_10",
      competencyKey: "clarity.progression",
      prompt: "A topic is in Clarity / High Maintenance and the full session scores strongly enough to advance. What should happen?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The Specialist manually moves it to Controlled Discomfort" },
        { key: "b", label: "The engine progresses the topic to Structured Execution at Low" },
        { key: "c", label: "The topic skips directly to Time Pressure Stability" },
        { key: "d", label: "Nothing can ever progress from Clarity" },
      ],
      correctOptionKeys: ["b"],
      explanation: "Clarity progression remains system-controlled and advances into Structured Execution, not by manual Specialist choice.",
    },
    {
      key: "clarity_logging_11",
      competencyKey: "evidence.logging_integrity",
      prompt: "Which logging behavior violates Response Integrity evidence rules?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Recording exactly what was observed" },
        { key: "b", label: "Leaving an observation unselected when it was not seen" },
        { key: "c", label: "Softening a weak rep because the student improved later" },
        { key: "d", label: "Using the registered observation options" },
      ],
      correctOptionKeys: ["c"],
      explanation: "Historical rep evidence must not be softened or rewritten to fit a desired outcome.",
    },
    {
      key: "clarity_constraints_12",
      competencyKey: "clarity.constraints",
      prompt: "Select all constraints that belong to Clarity.",
      kind: "multi_select",
      options: [
        { key: "a", label: "No Boss Battles" },
        { key: "b", label: "No time pressure" },
        { key: "c", label: "No skipping layers" },
        { key: "d", label: "Timer must be active" },
      ],
      correctOptionKeys: ["a", "b", "c"],
      explanation: "Clarity protects concept-entry structure before high difficulty and time pressure are introduced.",
    },
    {
      key: "clarity_rep_purpose_13",
      competencyKey: "clarity.rep_purpose",
      prompt: "Why is another repetition run inside a defined Clarity set?",
      kind: "single_choice",
      options: [
        { key: "a", label: "To create another controlled evidence opportunity under the same purpose" },
        { key: "b", label: "To fill time" },
        { key: "c", label: "To let the Specialist change the drill objective" },
        { key: "d", label: "To guarantee the student eventually gets a correct answer" },
      ],
      correctOptionKeys: ["a"],
      explanation: "A rep is another controlled opportunity to observe whether the targeted response is present.",
    },
    {
      key: "clarity_adaptation_14",
      competencyKey: "discernment.escalation_boundary",
      prompt: "The Specialist encounters a situation not covered by the active recipe and cannot preserve the required condition safely. What is the strongest response?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Invent a new protocol and continue" },
        { key: "b", label: "Preserve what can be preserved, record the deviation, and escalate rather than invent authority" },
        { key: "c", label: "Mark the session successful regardless" },
        { key: "d", label: "Change the student's phase manually" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["c", "d"],
      explanation: "Discernment includes knowing when to escalate. It does not authorize invention or state override.",
    },
    {
      key: "clarity_transfer_15",
      competencyKey: "clarity.transfer",
      prompt: "A student can explain the method but only starts solving after the Specialist gives the first step. What does this most directly tell you?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Correct explanation alone proves independent execution" },
        { key: "b", label: "Understanding may be present, but independent execution has not yet been demonstrated" },
        { key: "c", label: "The student should immediately enter Time Pressure Stability" },
        { key: "d", label: "The Specialist should ignore the prompted start" },
      ],
      correctOptionKeys: ["b"],
      explanation: "RI separates understanding from independent execution and preserves the evidence distinction between them.",
    },
  ],
};
