import type { CapabilityAssessmentDefinition } from "./capabilityEngine";

export const STRUCTURED_EXECUTION_MASTERY_ASSESSMENT: CapabilityAssessmentDefinition = {
  key: "structured_execution_mastery_v1",
  deepDiveKey: "structured_execution",
  title: "Structured Execution Mastery Check",
  evidenceKind: "mastery",
  passThresholdPercent: 96,
  questions: [
    {
      key: "structured_purpose_01",
      competencyKey: "structured_execution.phase_purpose",
      prompt: "What is Structured Execution primarily trying to prove?",
      kind: "single_choice",
      options: [
        { key: "a", label: "That the student can tolerate maximum difficulty" },
        { key: "b", label: "That a known method can be executed independently and repeatably" },
        { key: "c", label: "That the student can work under a timer" },
        { key: "d", label: "That the Specialist can reteach the topic" },
      ],
      correctOptionKeys: ["b"],
      explanation: "Structured Execution turns clarity into independent, repeatable method use before difficulty or time pressure are introduced.",
    },
    {
      key: "structured_required_structure_02",
      competencyKey: "structured_execution.required_structure",
      prompt: "The student reaches the correct answer but skips the required method sequence. How should the rep be treated?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Clear because the answer is correct" },
        { key: "b", label: "Not clear because structure-before-answer was not demonstrated" },
        { key: "c", label: "Automatically progress the topic" },
        { key: "d", label: "Let the Specialist decide from intuition" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["a"],
      explanation: "A lucky or shortcut answer does not prove the required visible method chain.",
    },
    {
      key: "structured_independence_03",
      competencyKey: "structured_execution.independent_execution",
      prompt: "During Independent Execution, what support level should the Specialist preserve?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Step-by-step guidance" },
        { key: "b", label: "First-step prompting" },
        { key: "c", label: "No help while observing the full execution" },
        { key: "d", label: "Whatever support keeps the student moving" },
      ],
      correctOptionKeys: ["c"],
      criticalFailOptionKeys: ["d"],
      explanation: "Independent Execution is a no-help condition. Assistance would contaminate the evidence of independence.",
    },
    {
      key: "structured_variation_04",
      competencyKey: "structured_execution.variation_control",
      prompt: "What makes the Variation Control set valid?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The same problem is repeated until memorized" },
        { key: "b", label: "A changed-form problem is presented without pointing out what changed" },
        { key: "c", label: "The Specialist explains the variation before the student begins" },
        { key: "d", label: "The problem is made easier if hesitation appears" },
      ],
      correctOptionKeys: ["b"],
      explanation: "Variation Control tests whether the same method survives a changed surface form without Specialist-led noticing.",
    },
    {
      key: "structured_pressure_05",
      competencyKey: "structured_execution.constraints",
      prompt: "Which constraints belong to Structured Execution?",
      kind: "multi_select",
      options: [
        { key: "a", label: "No Boss Battles" },
        { key: "b", label: "No timed pressure" },
        { key: "c", label: "Independent execution must not be rescued" },
        { key: "d", label: "Repeated timer pressure is required" },
      ],
      correctOptionKeys: ["a", "b", "c"],
      explanation: "Structured Execution is still a no-pressure phase focused on method discipline, independence and repeatability.",
    },
    {
      key: "structured_hesitation_06",
      competencyKey: "structured_execution.independent_execution",
      prompt: "The student hesitates after starting an independent rep. What is the strongest Specialist response?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Immediately provide the next step" },
        { key: "b", label: "Preserve the no-help condition long enough to observe whether the student can continue" },
        { key: "c", label: "End the rep and mark it failed" },
        { key: "d", label: "Change the phase manually" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["d"],
      explanation: "Hesitation is evidence. Rescuing too quickly destroys the observation the rep exists to produce.",
    },
    {
      key: "structured_observation_07",
      competencyKey: "evidence.observation_vs_inference",
      prompt: "Which note is valid Structured Execution evidence?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The student is careless" },
        { key: "b", label: "The student skipped step two on the first rep and preserved the sequence on the next two" },
        { key: "c", label: "The student lacks discipline" },
        { key: "d", label: "The student probably panicked" },
      ],
      correctOptionKeys: ["b"],
      explanation: "RI records observable execution behavior rather than inferred character or psychology.",
    },
    {
      key: "structured_contamination_08",
      competencyKey: "evidence.contamination",
      prompt: "The Specialist gives two prompts during a no-help rep and the student then finishes correctly. What can be claimed?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Independent execution was proven" },
        { key: "b", label: "The rep was assisted and cannot prove independent execution" },
        { key: "c", label: "The student is ready for time pressure" },
        { key: "d", label: "The prompts can be omitted from the log because the final answer was correct" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["a", "d"],
      explanation: "Assistance must remain visible in the evidence and cannot be relabeled as independence.",
    },
    {
      key: "structured_same_form_09",
      competencyKey: "structured_execution.variation_control",
      prompt: "Three correct same-form repetitions are completed. What do they prove about variation control?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Variation control is fully proven" },
        { key: "b", label: "Nothing yet about changed-form transfer; a changed-form opportunity is still required" },
        { key: "c", label: "The topic should skip to Time Pressure Stability" },
        { key: "d", label: "The Specialist can record the repetitions as changed-form evidence" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["d"],
      explanation: "Same-form repetition and changed-form transfer are different evidence conditions.",
    },
    {
      key: "structured_progression_10",
      competencyKey: "structured_execution.progression",
      prompt: "A topic reaches qualifying High Maintenance evidence in Structured Execution. What controls the next phase movement?",
      kind: "single_choice",
      options: [
        { key: "a", label: "The Specialist manually moves the topic" },
        { key: "b", label: "The RI engine decides whether it progresses into Controlled Discomfort at Low" },
        { key: "c", label: "The parent chooses the phase" },
        { key: "d", label: "The topic automatically jumps to the final phase" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["a"],
      explanation: "The Specialist captures evidence; the engine owns progression decisions.",
    },
    {
      key: "structured_recipe_11",
      competencyKey: "structured_execution.recipe_sequence",
      prompt: "Put the Structured Execution training recipe in the correct order.",
      kind: "sequence",
      options: [
        { key: "require", label: "Require structure" },
        { key: "withhold", label: "Withhold help" },
        { key: "variation", label: "Test variation" },
        { key: "submit", label: "Submit evidence" },
        { key: "engine", label: "Let RI-OS decide what happens next" },
      ],
      correctOptionKeys: ["require", "withhold", "variation", "submit", "engine"],
      explanation: "The Deep Dive defines this sequence as the operating mental model for Structured Execution.",
    },
    {
      key: "structured_repetition_12",
      competencyKey: "structured_execution.repeatability",
      prompt: "Why are multiple reps required after one successful structured attempt?",
      kind: "single_choice",
      options: [
        { key: "a", label: "To prove the method chain is repeatable rather than an isolated success" },
        { key: "b", label: "To fill the session" },
        { key: "c", label: "To increase the student's marks immediately" },
        { key: "d", label: "To give the Specialist more opportunities to explain" },
      ],
      correctOptionKeys: ["a"],
      explanation: "The phase is explicitly concerned with repeatable execution, not one good attempt.",
    },
    {
      key: "structured_heavy_remodel_13",
      competencyKey: "structured_execution.phase_boundary",
      prompt: "The student cannot state the known method without heavy remodelling from the Specialist. What does that evidence suggest?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Keep manufacturing Structured Execution success with more prompts" },
        { key: "b", label: "The topic may not yet belong in Structured Execution; preserve the evidence and let the system determine state" },
        { key: "c", label: "Introduce a timer to force independence" },
        { key: "d", label: "Record the prompted execution as independent" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["d"],
      explanation: "Heavy remodelling signals that the prerequisite clarity/structure may not be sufficiently established.",
    },
    {
      key: "structured_escalation_14",
      competencyKey: "discernment.escalation_boundary",
      prompt: "A live situation falls outside the recipe and the Specialist cannot preserve the required condition confidently. What should happen?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Invent a new rule and continue" },
        { key: "b", label: "Record the deviation, preserve what can safely be preserved, and escalate" },
        { key: "c", label: "Mark the rep clear to avoid disrupting the session" },
        { key: "d", label: "Change the student's state manually" },
      ],
      correctOptionKeys: ["b"],
      criticalFailOptionKeys: ["c", "d"],
      explanation: "Discernment includes knowing the boundary of Specialist authority and escalating rather than inventing protocol.",
    },
    {
      key: "structured_transfer_15",
      competencyKey: "structured_execution.phase_boundary",
      prompt: "The student can name the method and explain why it works, but repeatedly waits for Specialist direction before each step. What has not yet been established?",
      kind: "single_choice",
      options: [
        { key: "a", label: "Concept recognition" },
        { key: "b", label: "Independent structured execution" },
        { key: "c", label: "Vocabulary" },
        { key: "d", label: "A need for immediate time pressure" },
      ],
      correctOptionKeys: ["b"],
      explanation: "Understanding the method and independently executing it are deliberately separate capability claims in RI.",
    },
  ],
};
